#index:
#    path: /
#    controller: App\Controller\DefaultController::index


vessel_post_track:
    path: /api/vessels
    methods: ['POST']
    defaults:
        _controller: App\Controller\VesselController::create
        _api_resource_class: App\Entity\Vessel
        _api_collection_operation_name: post_track